import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './css/style.scss'

import BootstrapClient from './components/BootstrapClient'
import Script from 'next/script'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <BootstrapClient />
        <Script src="/js/jquery.js"></Script> 
        <Script src="/js/main.js"></Script> 
      </body>
    </html>
  )
}
